twig:
    file_name_pattern: "*.twig"
    default_path: "%kernel.project_dir%/templates"
    form_themes:
        - "form/tailwind_form.html.twig"

when@test:
    twig:
        strict_variables: true
