controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Redirect root (/) to /home
default_redirect:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: home
        permanent: true  # Set false if you want a temporary redirect (302)
